/* 
  Sketch generated by the Arduino IoT Cloud Thing "LED try 2"
  https://create.arduino.cc/cloud/things/25825b3c-7dc8-414b-babe-07b078a7b739 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool LED;
  bool SWITCH;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

int hallwayLED = 7;
int porchLED = 5;

unsigned long porchTime = 0;
unsigned long hallwayTime = 0;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  pinMode(hallwayLED, OUTPUT);
  pinMode(porchLED, OUTPUT);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
   
  checkTimes();
}

void checkTimes() {
  if (hallwayTime && millis() >= hallwayTime) {
    digitalWrite(hallwayLED, LOW);
    hallwayTime = 0;
  }
  if (porchTime && millis() >= porchTime) {
    digitalWrite(porchLED, LOW);
    porchTime = 0;
  }
}


void onSWITCHChange()  {
  if(SWITCH){
    digitalWrite(hallwayLED, HIGH);
    digitalWrite(porchLED, HIGH);
    
    hallwayTime = millis() + 60000;  //60 secs
    porchTime = millis() + 30000; //30 secs
    
    SWITCH = false;
  }
}